docker_forhw1/docker-deploy/web-app/homework1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('myuser/', include('myuser.urls')),
    path('admin/', admin.site.urls),
]

docker_forhw1/docker-deploy/web-app/myuser/urls.py
from django.urls import path
from . import views

app_name='myuser'
urlpatterns = [
    path('', views.home, name='home'),  ##leave as empty first argument if you want it to be home page
    #path('register/', views.register, name='register'),
    #path('login/', auth_views.LoginView.as_view(template_name='myuser/login.html'), name='login'),
    #path('logout/',  views.logout, name='logout'),
 path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('<int:id>/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('<int:id>/driverreg/', views.driverreg, name='driverreg'),
    path('<int:id>/editdriver/', views.editdriver, name='editdriver'),
    path('<int:id>/newtrip/', views.newtrip, name='newtrip'),
    path('<int:id>/<int:tid>/optpsg/', views.optpsg, name='optpsg'),
    path('<int:id>/tripava/', views.tripava, name='tripava'),
    path('<int:id>/<int:tid>/confirmtrip/', views.confirmtrip, name='confirmtrip'),
    path('<int:id>/<int:tid>/optdriver/', views.optdriver, name='optdriver'),
    path('<int:id>/changeemail/', views.changeemail, name='changeemail'),
    #path(r'myuser\\/(?P<id>[0-9]+)\\/(?P<p_id>[0-9]+)\\/optpsg\\/$/', views.optpsg, name='optpsg'),
]

docker_forhw1/docker-deploy/web-app/myuser/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import datetime
from django.contrib.postgres.fields import ArrayField

def emptylist():
    return [];

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    driver = models.BooleanField(default=False)
    psg = models.BooleanField(default=False)
    share = models.BooleanField(default=False)
    vehicle = models.CharField(max_length=20, blank=True)
    plate = models.CharField(max_length=10, blank=True)
    capacity = models.IntegerField(default=1, validators=[MaxValueValidator(100), MinValueValidator(1)])
    special = models.CharField(max_length=200, blank=True, default='')

class Trip(models.Model):  
    destination = models.CharField(max_length=50, blank=False)
    arrivaltime = models.DateTimeField()
    passenger = models.IntegerField(validators=[MaxValueValidator(100),MinValueValidator(1)])
    ifshare = models.BooleanField(default=False)
    vehicle = models.CharField(max_length=20, blank=True)
    d_id = models.IntegerField(default=-1, blank=True)
    p_id = models.IntegerField(default=-1, blank=False)
    status = models.CharField(max_length=10, default='open')
   

docker_forhw1/docker-deploy/web-app/myuser/forms.py
from django import forms
from django.contrib.auth.models import User
import re;
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.postgres.fields import ArrayField

def valid_email(email):
    pattern = re.compile(r"\"?([-a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?")
    return re.match(pattern, email)

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=40)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)


        
        
class RegForm(forms.Form):
    username = forms.CharField(label='Username', max_length=50,help_text='username should be less than 50 characters')
    first_name = forms.CharField(label='Firstname', max_length=40,help_text='first name should be less than 40 characters')
    last_name = forms.CharField(label='Lastname', max_length=40,help_text='last name should be less than 40 characters')
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)

   


class DriverForm(forms.Form):
    vehicle = forms.CharField(label='vehicle type', max_length=20)
    plate = forms.CharField(label='plate', max_length=10)
    capacity = forms.IntegerField(label='capacity', validators=[MaxValueValidator(100),MinValueValidator(1)])
   

 

class TripForm(forms.Form):
    destination = forms.CharField(label='destination', max_length=50)
    arrivaltime = forms.DateTimeField(label='arrivaltime', help_text=' e.g.: 12/27/2018 16:17')
    passenger = forms.IntegerField(label='number of passengers', validators=[MaxValueValidator(100),MinValueValidator(1)])
    ifshare = forms.BooleanField(label='willing to share?', required=False)
    
    
class UserEmailForm(forms.Form):
    email = forms.EmailField(label='email')
    def clean_email(self):
        email = self.cleaned_data.get('email')
        return email



docker_forhw1/docker-deploy/web-app/myuser/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from .models import UserProfile, Trip
from django.contrib import auth
from .forms import RegForm, LoginForm,DriverForm,TripForm,UserEmailForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Q



def home(request):
    return render(request, 'myuser/home.html')


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect("/myuser/")
    


def register(request):
    if request.method == 'POST':
        form = RegForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password2']

            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name, password=password, email=email)

            userprofile = UserProfile(user=user)
            userprofile.save()
            messages.success(request, 'Your account has been created. '
                             'You are now able to log in!')
            return HttpResponseRedirect("/myuser/login/")

    else:
        form = RegForm()

    return render(request, 'myuser/register.html', {'form':form})

# login into your account
def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = auth.authenticate(username=username, password=password)

            if user is not None and user.is_active:
                auth.login(request, user)
                messages.success(request, 'Login successfully!')
                return HttpResponseRedirect(reverse('myuser:profile', args=[user.id]))
            else:
                return render(request, 'myuser/login.html', {'form':form, 'message': 'Wrong password. Please try again.'})

    else:
        form = LoginForm()

    return render(request, 'myuser/login.html', {'form': form})
    
@login_required
def profile(request, id):
    user = get_object_or_404(User, id=id)
    userprofile = get_object_or_404(UserProfile, user=user)
    
    
#    tripasdriver= Trip.objects.filter(d_id=id)
#    tripaspsg= Trip. objects.filter(p_id=id)
    
#    context={
#    'tripasdriver':tripasdriver,
#    'tripaspsg':tripaspsg,
#    }
    return render(request, 'myuser/profile.html', {'user': user, 'userprofile':userprofile})
    


@login_required
def driverreg(request, id):
    user = get_object_or_404(User, id=id)
    userprofile = get_object_or_404(UserProfile, user=user)

    if request.method == 'POST':
        form = DriverForm(request.POST)

        if form.is_valid():
            userprofile.driver = True
            userprofile.vehicle = form.cleaned_data['vehicle']
            userprofile.plate = form.cleaned_data['plate']
            userprofile.capacity = form.cleaned_data['capacity']
            userprofile.save()

            return HttpResponseRedirect(reverse('myuser:profile', args=[user.id]))

    else:
        form = DriverForm()

    return render(request, 'myuser/driverreg.html', {'form': form, 'user': user})



@login_required
def editdriver(request, id):
    user = get_object_or_404(User, id=id)
    userprofile = get_object_or_404(UserProfile, user=user)

    if request.method == 'POST':
        form = DriverForm(request.POST)

        if form.is_valid():
            userprofile.vehicle = form.cleaned_data['vehicle']
            userprofile.plate = form.cleaned_data['plate']
            userprofile.capacity = form.cleaned_data['capacity']
            userprofile.save()
            messages.success(request, 'Successfully logged in!')
            return HttpResponseRedirect(reverse('myuser:profile', args=[user.id]))
    else:
        context = {
            'vehicle': userprofile.vehicle,
            'plate': userprofile.plate,
            'capacity': userprofile.capacity,
            'special': userprofile.special,
        }
        form = DriverForm(context)

        return render(request, 'myuser/editdriver.html', {'user': user, 'userprofile': userprofile, 'form': form})


@login_required
def newtrip(request, id):
    user = get_object_or_404(User, id=id)
    userprofile = get_object_or_404(UserProfile, user=user)
    
    if request.method == 'POST':
        form = TripForm(request.POST)

        if form.is_valid():
            destination = form.cleaned_data['destination']
            arrivaltime = form.cleaned_data['arrivaltime']
            passenger = form.cleaned_data['passenger']
            ifshare = form.cleaned_data['ifshare']
            #p_id=id;

            trip = Trip(destination=destination, arrivaltime=arrivaltime, passenger=passenger, ifshare=ifshare,p_id=id)
            #t_id=trip.id
            trip.save()
            messages.success(request, 'Your driver is on the way!')
            #return render(request, 'myuser/optpsg.html', {'form': form, 'trip':trip, 'user': user})
            return HttpResponseRedirect(reverse('myuser:optpsg', args=(user.id,trip.id)))
              
    else:
        form = TripForm()
    return render(request, 'myuser/newtrip.html', {'form': form, 'user': user})

@login_required
def optpsg(request, id,tid):
    user = get_object_or_404(User, id=id)
    trip = get_object_or_404(Trip, id=tid)
    
    if request.method == 'POST':
        form = TripForm(request.POST)

        if form.is_valid():
            trip.destination = form.cleaned_data['destination']
            trip.arrivaltime = form.cleaned_data['arrivaltime']
            trip.passenger = form.cleaned_data['passenger']
            trip.ifshare = form.cleaned_data['ifshare']
            trip.p_id = id

            #trip = Trip(destination=destination, arrivaltime=arrivaltime, passenger=passenger, ifshare=ifshare, p_id=p_id)
            trip.save()
            messages.success(request, 'Your have changed your trip information!')
            return HttpResponseRedirect(reverse('myuser:optpsg', args=[user.id,trip.id]))
    else:
        context = {
            'destination': trip.destination,
            'arrivaltime': trip.arrivaltime,
            'passenger': trip.passenger,
            'ifshare': trip.ifshare,
            'p_id':trip.p_id,
        }
        form = TripForm(context)
    return render(request, 'myuser/optpsg.html', {'form': form, 'user': user, 'trip':trip})

#@login_required
#def optpsg(request,p_id):
#    #trip = get_object_or_404(Trip, id=p_id)
#    return render(request, 'myuser/optpsg.html',)

@login_required
def tripava(request, id):
    user = get_object_or_404(User, id=id)
    userprofile = get_object_or_404(UserProfile, user=user)
    suitable = Trip.objects.filter(Q(vehicle=userprofile.vehicle,status='open') | Q(vehicle='',status='open'))
    #suitable = Trip(vehicle=userprofile.vehicle, status='open') | Trip (vehicle= '',status='open')
    temp = list(suitable)
    avatrip = []
    for trip in temp:
        num = trip.passenger
        if num <= userprofile.capacity:
            avatrip.append(trip)
    
    return render(request, 'myuser/tripava.html', {'user': user, 'userprofile': userprofile, 'avatrip': avatrip})
    
    
@login_required
def confirmtrip(request,id, tid):
    user = get_object_or_404(User, id=id)
    trip = get_object_or_404(Trip, id=tid) 
    if trip.status == 'open':
        trip.status = 'confirmed'
        trip.d_id=id
        trip.save()

    return render(request, 'myuser/confirmtrip.html', {'user':user,'trip':trip})


#@login_required
#def managepage(request, id):
#    user = get_object_or_404(User, id=id)
#    userprofile = get_object_or_404(UserProfile, user=user)
#    
#    tripasdriver= Trip.objects.filter(d_id=id)
#    tripaspsg= Trip. objects.filter(p_id=id)
#    
#    return render(request, 'myuser/profile.html', {'user': user, 'userprofile':userprofile,'tripasdriver':tripasdriver,'tripaspsg':tripaspsg})



@login_required
def optdriver(request, id,tid):
    user = get_object_or_404(User, id=id)
    trip = get_object_or_404(Trip, id=tid)
    
    if request.method == 'POST':
        form = TripForm(request.POST)

        if form.is_valid():
            trip.destination = form.cleaned_data['destination']
            trip.arrivaltime = form.cleaned_data['arrivaltime']
            trip.passenger = form.cleaned_data['passenger']
            trip.ifshare = form.cleaned_data['ifshare']
            trip.d_id = id

            #trip = Trip(destination=destination, arrivaltime=arrivaltime, passenger=passenger, ifshare=ifshare, p_id=p_id)
            trip.save()
            messages.success(request, 'Your have changed your trip information!')
            return HttpResponseRedirect(reverse('myuser:optdriver', args=[user.id,trip.id]))
    else:
        context = {
            'destination': trip.destination,
            'arrivaltime': trip.arrivaltime,
            'passenger': trip.passenger,
            'ifshare': trip.ifshare,
            'd_id':trip.d_id,
        }
        form = TripForm(context)
    return render(request, 'myuser/optpsg.html', {'form': form, 'user': user, 'trip':trip})
    
@login_required
def changeemail(request,id):
    user= get_object_or_404(User,id=id)
    userprofile = get_object_or_404(UserProfile, user=user)
    if request.POST:
       form=UserEmailForm(request.POST)
       if form.is_valid():

docker_forhw1/docker-deploy/web-app/myuser/templates/myuser/base.html

<!DOCTYPE html>
<html lang="en">
<head>
    {% if title%}
    <title>Django Myuser -{{ title }}</title>
    {% else %}
    <title>Django Myuser</title>
    {% endif %}
    
    <style>
h2 {color:red;}
p {color:blue;}
</style>

</head>
<body>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
        {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% block content %}{% endblock %}
</body>
</html>

docker_forhw1/docker-deploy/web-app/myuser/templates/myuser/changeemail.html
{% extends 'myuser/base.html'%}
    {% block content %}
    <h2>Email Information</h2>
    <ul>
        <li>username: {{ user.username }}</li>
        <li>email: {{ user.email }}</li>
    </ul>

    {% if message %}
    {{ message }}
    {% endif %}

    <h2>Email Change</h2>
    <div class="form-wrapper">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="field-wrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    {{ field.help_text|safe }}
                {% endif %}
            </div>
            {% endfor %}
            <div class="button-wrapper submit"><input type="submit" value="Submit"></div>
        </form>
        <a href="{% url 'myuser:profile' user.id%}">Profile</a>
    </div>
    {% endblock %}

docker_forhw1/docker-deploy/web-app/myuser/templates/myuser/confirmtrip.html
{% extends 'myuser/base.html'%}
{% block content %}
    <ul>
    <p>You chose to pick a passenger to {{ trip.destination }} by {{ trip.arrivaltime }}, enjoy your ride!</p>
    </ul>
    <br>
    <button class="btn btn-outline-info" type="button"><a href="{% url 'myuser:profile' user.id %}">Profile</a></button>
    {% endblock %}

docker_forhw1/docker-deploy/web-app/myuser/templates/myuser/editdriver.html
{% extends "myuser/base.html" %}
{% block content %}
    <h2>Personal Information</h2>
    <ul>
        <li>Username: {{ user.username }}</li>
        <li>Email: {{ user.email }}</li>
    </ul>

    <h2>Driver Information</h2>
    <div class="form-wrapper">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="field-wrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    {{ field.help_text|safe }}
                {% endif %}
            </div>
            {% endfor %}
            <button class="btn btn-outline-info" type="submit">Submit</a></button>
        </form>
        <button class="btn btn-outline-info" type="button"><a href="{% url 'myuser:profile' user.id%}">Profile</a></button>
    </div>
    {% endblock %}

docker_forhw1/docker-deploy/web-app/myuser/templates/myuser/home.html
{% extends 'myuser/base.html' %}
    {% block content %}
    <h1>Enjoy you trip!</h1>
    <a href="{% url 'myuser:register' %}">Register now!</a>
    <a href="{% url 'myuser:login' %}">Login</a>
    {% endblock %}

docker_forhw1/docker-deploy/web-app/myuser/templates/myuser/login.html
{% extends 'myuser/base.html'%}

    {% block content %}

   <h2>Login</h2>

    {% if message %}
    {{ message }}
    {% endif %}

    {% if next %}
    <p>Hey, you cannot access that page.</p>
    {% endif %}

    <div class="form-wrapper">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="field-wrapper">
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="button-wrapper submit">
                    <p><input type="submit" value="Login"></p>
            </div>
        </form>
        <a href="/myuser/register/">Register</a>
    </div>
    {% endblock %}


docker_forhw1/docker-deploy/web-app/myuser/templates/myuser/managepage.html
{% extends "myuser/base.html" %}
{% block content %}
   <h2>Manage Page</h2>
    

    {% endblock %}

docker_forhw1/docker-deploy/web-app/myuser/templates/myuser/newtrip.html
{% extends "myuser/base.html" %}
{% block content %}
    <h2>Trip Information</h2>
    <br>
    <div class="form-wrapper">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="field-wrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    {{ field.help_text|safe }}
                {% endif %}
            </div>
            {% endfor %}
                        
            
            
            <button class="btn btn-outline-info" type="submit">Start a new trip!</button>
           
        </form>
        <a href="{% url 'myuser:profile' user.id%}">Profile</a>
    </div>
    {% endblock %}

docker_forhw1/docker-deploy/web-app/myuser/templates/myuser/optdriver.html
{% extends "myuser/base.html" %}
{% block content %}
    <h2>Trip Information</h2>
    <br>
    <div class="form-wrapper">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="field-wrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    {{ field.help_text|safe }}
                {% endif %}
            </div>
            {% endfor %}
            <button class="btn btn-outline-info" type="submit">Update the trip</a></button>
            <!--{% if trip.is_authenticated %}-->
            
            <!--{%endif%}-->
        </form>
        <ul>
        <li>destination: {{ trip.destination }}</li>
            <li>arrivaltime: {{ trip.arrivaltime }}</li>
            <li>passenger: {{ trip.passenger }}</li>
        </ul>
        <a href="{% url 'myuser:profile' user.id%}">Profile</a>
    </div>
    {% endblock %}

docker_forhw1/docker-deploy/web-app/myuser/templates/myuser/optpsg.html
{% extends "myuser/base.html" %}
{% block content %}
    <h2>Trip Information</h2>
    <br>
    <div class="form-wrapper">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="field-wrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    {{ field.help_text|safe }}
                {% endif %}
            </div>
            {% endfor %}
            <button class="btn btn-outline-info" type="submit">Update the trip</a></button>
            <!--{% if trip.is_authenticated %}-->
            
            <!--{%endif%}-->
        </form>
        <ul>
        <li>destination: {{ trip.destination }}</li>
            <li>arrivaltime: {{ trip.arrivaltime }}</li>
            <li>passenger: {{ trip.passenger }}</li>
        </ul>
        <a href="{% url 'myuser:profile' user.id%}">Profile</a>
    </div>
    {% endblock %}

docker_forhw1/docker-deploy/web-app/myuser/templates/myuser/profile.html

{% extends "myuser/base.html" %}
{% block content %}
   <h2>Personal Information</h2>
    <ul>
        <li>username: {{ user.username }}</li>
        <li>email: {{ user.email }}</li>
    </ul>

    <h2>My Profile</h2>
    <ul>
        <li>first name: {{ user.first_name }}</li>
        <li>last name: {{ user.last_name }}</li>
        {% if userprofile.driver %}
        <p>Driver Information</p>
        <li>vehicle: {{ userprofile.vehicle }}</li>
        <li>plate: {{ userprofile.plate }}</li>
        <li>passenger cetapacity: {{ userprofile.capacity }}</li>
        {% if userprofile.special %}
        <li>Special Info: {{ userprofile.special}}</li>
        {% endif %}
        {% endif %}
         
         {% if user.is_authenticated %}
         <button class="btn btn-outline-info" type="button"><a href="{% url 'myuser:newtrip' user.id  %}">Start a new trip as a passenger!</a></button> 
         <button class="btn btn-outline-info" type="button"><a href="{% url 'myuser:changeemail' user.id  %}">change email</a></button> 
        {% if not userprofile.driver %}
        <button class="btn btn-outline-info" type="button"><a href="{% url 'myuser:driverreg' user.id %}">DriverRegistration</a></button>
        
        {% else %}
        <button class="btn btn-outline-info" type="button"><a href="{% url 'myuser:editdriver' user.id %}">Change driver's information</a></button>
        <button class="btn btn-outline-info" type="button"><a href="{% url 'myuser:tripava' user.id %}">Search for a new trip as a driver!</a></button>
        {%endif%}
         <br>
       
        {% endif %}
        <br>
        
       
        
        <button class="btn btn-outline-info" type="button"><a href="{% url 'myuser:logout' %}">Log out</a></button>
        
    </ul>

    {% endblock %}

docker_forhw1/docker-deploy/web-app/myuser/templates/myuser/register.html
{% extends "myuser/base.html" %}
{% block content %}
   
    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.errors }}
                    {{ field.label_tag}} {{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <input type="submit" value="Submit">
        </form>
    </div>
  
{% endblock content %}

docker_forhw1/docker-deploy/web-app/myuser/templates/myuser/tripava.html
{% extends 'myuser/base.html'%}
{% block content %}

    <ol>Choose a customer to pick up
    
        {% for trip in avatrip %}
        <li>
            <p>destination: {{ trip.destination }} anticipated arrival time: {{ trip.arrivaltime }}</p>
            <p>number of passenger: {{ trip.passenger }}</p>      
        </li>
            <button class="btn btn-outline-info" type="button"><a href="{% url 'myuser:confirmtrip' user.id trip.id %}">Pick</a></button>
            <button class="btn btn-outline-info" type="button"><a href="{% url 'myuser:optdriver' user.id trip.id %}">Edit existed trip</a></button>
        <br>
        {% endfor %}
    </ol>
    <br>
    <a href="{% url 'myuser:profile' user.id %}">Profile</a>
    {% endblock %}